defaults : &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development: &DEV
  <<: *defaults
  database: blog_development

production: &DEV
  <<: *defaults
  database: blog_production

test: &TEST
  <<: *defaults
  database: blog_test
